import './globals.css'

import {
  Inter
} from 'next/font/google'

const inter = Inter({
  subsets: ['cyrillic-ext']
})

export const metadata = {
  title: 'Sestry jeveleries',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}) {
  return (
    <html lang="en">
    <body className={ inter.className }>
      { children }
    </body>
    </html>
  )
}